print("Multiplicação * ", 10 * 10)
print("Divisão / ", 10 / 3)
print("Adição + ", 10 + 10)
print("Subtração * ", 10 - 2)
print("Concatenação ", '10' + '2')
print("Divisão parte inteira ", 10 // 3)
print("Exponenciação", 2 ** 3)
print("Módulo - resto da divisão", 10 % 2)